### ISSUE TITLE
Is there a way make the help window use the Dracula theme?

### ISSUE THREAD

**Issue by roiholtzman** [jldohmann/wolfram-notebooks#5]
It would be great if the help window (the one that opens when one hits `F1`) would also have Dracula theme. Can this be done?

**Comment by jldohmann** [comment]
@roiholtzman are you referring to the Documentation Center? Could you please post a screenshot? I am not always using the machine with my copy of M- and I have modified keyboard shortcuts/macros anyway 🙂

**Comment by jldohmann** [comment]
The notebooks launched from the documentation center use their own specific stylesheets which have more style definitions than the default style, for example, because of all the extra formatting involved and [it's tricky to override these definitions](https://mathematica.stackexchange.com/questions/143596/how-to-override-the-style-definitions-in-reference-nb). 

So even if you apply the Dracula theme to documentation notebooks, the theme was implemented around the default stylesheet use case and will not cover these extra style definitions without modification.

You could see how the Dracula theme would look though, by applying the stylesheet directly to any open documentation notebook:

```
SetOptions[nbObj, StyleDefinitions -> "Dracula.nb"]
```
